title: My profile
author: Lenur
email: bl***@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my profile and it will be gradually fill up.
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
